In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('EntranceExam2.csv')
df

,Timestamp,Courses in Probability and Statistics,"Suppose that after flipping a biased coin n times you know what that the bias of the coin is in the range [0.7,0.8] with probability 95%. What is the number of times you would need in order to half the length of the interval, keeping the probability at 95%.",Suppose X and Y are independent random variables such that Var(X)=1 and Var(Y)=2. What is the variance of X+2Y-3,"X and Y are random variables that take on the values 1,2,3. We use P(x,y) as shorthand for P(X=x,Y=y). You know that P(1,1)=P(3,1)=P(3,3)=1/8, P(2,1)=P(1,2)=P(2,3)=0; and that the marginals are P(X=1)=P(Y=1)=P(X=3)=P(Y=3)=1/4 and P(X=2)=P(Y=2)=1/2. Given that information, what can you say about X and Y?",Experience with Python,"input: a list of numbers L, output: the largest number in L","If you have experience using Hadoop, describe it here, using at most 400 characters.",Academic background,Name,PID,email,"Input: a list of numbers L, output: the sum of the squares of the values in L","Input: A list of numbers L, and a number a. Output: the numbers in the L that are smaller or equal to a"
0,2/24/2016 20:34:49,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if (x > y) else y, L)",NaN,First Year MSc in Computer Science & 4 year lo...,Qian Wang,A53088113,qiw087@eng.ucsd.edu,"reduce(lambda x, y: x + y, map(lambda x: x * x...","filter(lambda x: x <= a, L)"
1,2/25/2016 0:48:30,NaN,4n,9,Dependent and correlated,NaN,max(input),NaN,MSc,Caroline Kim,A53104857,chk101@eng.ucsd.edu,"sum(map(lambda x: x*x, input))","filter(lambda x: x <= a, L)"
2,2/25/2016 17:44:40,NaN,4n,9,Dependent and uncorrelated,NaN,"max = lambda input: reduce(lambda x,y : x if(x...",NaN,1st year MSc,Zhongrong Jian,A53096102,zhjian@ucsd.edu,"sum = lambda input: reduce(lambda x,y: x+y, (m...","seq = lambda input, a: list(filter(lambda x: x..."
3,2/25/2016 17:46:49,NaN,4n,9,Dependent and uncorrelated,NaN,"max = lambda list : reduce(lambda a, b : a if ...",NaN,MSc Computational Science (1st Year) - I did m...,Juan Sidrach de Cardona Mora,A53096298,jsidrach@ucsd.edu,"sumSq = lambda list : reduce(lambda a, b : a +...","filterList = lambda L, a : list(filter(lambda ..."
4,2/25/2016 17:48:32,NaN,4n,9,Dependent and uncorrelated,NaN,"maxL = lambda L : reduce (lambda a,b : a if (a...",NaN,1st year master,Lingyi Kong,A97010449,l1kong@ucsd.edu,"sqSum = lambda L : reduce (lambda a,b : a + b,...","smallL = lambda L,a : filter (lambda x : x < a..."
5,2/25/2016 17:52:03,NaN,4n,9,Dependent and uncorrelated,NaN,"maxL = lambda L : reduce (lambda a,b : a if (a...",NaN,1st year Master,Lingyi Kong,A97010449,l1kong@ucsd.edu,"sqSum = lambda L : reduce (lambda a,b : a + b,...","smallL = lambda L,a : filter(lambda x : x <= a..."
6,2/25/2016 18:11:26,NaN,4n,9,Dependent and uncorrelated,NaN,"max = lambda L : reduce(lambda a,b : a if (a >...",NaN,First year graduate student,Lu Yu,a53107397,luy018@ucsd.edu,"SoQ = lambda L : reduce (lambda x,y : x+y, map...","listfilter = lambda L, a : list(filter(lambda ..."
7,2/25/2016 18:35:22,NaN,4n,9,Independent and uncorrelated,NaN,"reduce(lambda x, y : x if x > y else y, input)",NaN,MS,Yuanchao Zhu,A53098001,yuz063@eng.ucsd.edu,"reduce(lambda x, y: x+y*y, input)","filter(lambda x: x<=a, input)"
8,2/25/2016 18:37:22,NaN,4n,9,Independent and uncorrelated,NaN,"reduce(lambda x,y: x if x > y else y, input)",NaN,MSc 2 quarters,Yuning Hui,A53091905,y3hui@eng.ucsd.edu,"reduce(lambda x,y: x+y, map(lambda x: x**2, in...","filter(lambda x: x <= a, L)"
9,2/25/2016 19:44:45,NaN,4n,5,Independent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b,[1,2,3,...",NaN,MSc CSE 1st year/4 year BSc in Statistics,Shen Ting ANg,A53095324,s3ang@eng.ucsd.edu,"reduce(lambda x,y:x+y,map(lambda x:x**2,[1,2,3...","filter(lambda x,a=3:x <=a,[1,2,3,4,5,6])"
10,2/25/2016 20:43:18,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y: x if x > y else y, input)",NaN,First year MSc,Zhe Wang,A53097553,zhw176@ucsd.edu,"reduce(lambda x,y: x+y ,map(lambda x: x**2, in...","filter(lambda x: x <= a, L)"
11,2/25/2016 20:45:53,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a>b) else b, L)",NaN,Master Student in CS,Qingyu Zhou,A53093706,qyzhou@ucsd.edu,"reduce(lambda a,b : a + b, map (lambda a: a * ...","filter(lambda x: x <=a, L)"
12,2/25/2016 20:49:14,NaN,2n,9,Dependent and uncorrelated,NaN,"output = reduce(lambda a, b: max(a, b), input)",NaN,"MSc, 1st year",Xu Hu,A53090833,xuh020@eng.ucsd.edu,"output = reduce(lambda a, b: a + b, map(lambda...","output = filter(lambda x: x <= a, L)"
13,2/25/2016 21:28:21,NaN,4n,9,Dependent and uncorrelated,NaN,"output = reduce(lambda x, y: max(x, y), input)",NaN,"MSc, 1st year",Junlong Hou,A53106567,juh097@ucsd.edu,"output = reduce(lambda x, y: x + y, map(lambda...","output = filter(lambda x: x <= a, L)"
14,2/25/2016 22:15:03,NaN,4n,9,Dependent and uncorrelated,NaN,"output = reduce(lambda x, y: x if (x>y) else y...",NaN,"MSc, first year",Siyuan Liu,A53099540,sil148@eng.ucsd.edu,"output = reduce(lambda x, y: x+y, map(lambda x...","output = filter(lambda x: x <= a, L)"
15,2/25/2016 22:22:08,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y : x if x > y else y, input)",NaN,MS,Yuanchao Zhu,A53098001,yuz063@eng.ucsd.edu,"reduce(lambda x, y: y*y + x, input)","filter(lambda x: x <= a, L)"
16,2/26/2016 2:17:17,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if(a>b) else b, L)",NaN,First year master student,Yu Shen,A53092101,yus067@ucsd.edu,"reduce(lambda a,b : a+b, map(lambda a: a*a, L))","filter(lambda x: x <= a, L)"
17,2/26/2016 5:19:18,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda a, b: a if (a > b) else b, x)",NaN,1st yr CS MSc,Zhimin Zhou,A53089795,zhz249@eng.ucsd.edu,"reduce(lambda a, b: a+b**2, x)","filter(lambda x: x <= a, L)"
18,2/26/2016 11:54:26,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce (lambda x, y : x if (x>y) else y, L)",NaN,"MSc, one year",Mubin Wang,A53091316,muw012@ucsd.edu,"reduce (lambda x, y : x + y, map (lambda x: x ...","filter (lambda x: x <= a, L)"
19,2/26/2016 13:28:44,NaN,4n,9,Dependent and correlated,NaN,"max = lambda list: reduce(lambda x,y:x if(x>y)...",NaN,MSc 2 years,Xiaojian Jin,A53104909,xij049@ucsd.edu,"sum = lambda list:reduce(lambda x,y:x+y, (map(...","smallereq = lambda list, a: list(filter(lambda..."
20,2/26/2016 13:37:21,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if(x > y) else y, nums)",NaN,First Year MS in CSME,Yiwen Shi,A53100492,yis018@ucsd.edu,"reduce(lambda x, y: x+y, map(lambda x: x*x, nu...","filter(lambda x: x <= a, L)"
21,2/26/2016 13:42:12,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,3rd year PhD in Mathematics with Specializatio...,Yue Xu,A53046117,yux033@ucsd.edu,"reduce(lambda x,y: x+y,map(lambda x: x*x, L))","filter(lambda x: x <= a, L)"
22,2/26/2016 13:48:25,NaN,4n,9,Dependent and correlated,NaN,f=lambda x: max(x),NaN,1st year Master,Yilin Zhai,A53103154,yizhai@ucsd.edu,"f= lambda x: sum(map(lambda a: a**2,x))","f= lambda a L:filter(lambda b: b<=a,L)"
23,2/26/2016 14:40:22,NaN,4n,9,Dependent and uncorrelated,NaN,"output=reduce(lambda a,b: a if (a > b) else b, L)",NaN,1st year ECE PhD,Chelin Huang,A53053719,chh163@eng.ucsd.edu,"output=reduce(lambda x,y: x+y, map(lambda x: x...","output=filter(lambda x: x <= a, L)"
24,2/26/2016 17:51:44,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda a, b: a if (a > b) else b, L)",NaN,1st yr CS MS,Zhimin Zhou,A53089795,zhz249@eng.ucsd.edu,"reduce(lambda a, b: a+b**2, L)","filter(lambda x:x!=0, map(lambda x, a:(x <= a..."
25,2/26/2016 17:53:18,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a>b) else b, L)",NaN,MS in CS First Year,Qingyu Zhou,A53093706,qyzhou@ucsd.edu,"reduce(lambda a,b : a + b, map (lambda a: a * ...","filter(lambda x: x <=a, L)"
26,2/26/2016 17:58:18,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce (lambda a,b: a if (a>b) else b, L)",NaN,1st year master,Lingyi Kong,A97010449,l1kong@ucsd.edu,"reduce (lambda a,b: a+b, map(lambda a: a**2,L))","filter (lambda x: x <= a, L)"
27,2/26/2016 17:58:20,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce (lambda a, b: a if (a > b) else b, L)",NaN,Computational Science (1st Year) - Undergrad i...,Juan Sidrach de Cardona Mora,A53096298,jsidrach@ucsd.edu,"reduce (lambda a, b: a + b, map(lambda a: a * ...","list (filter (lambda b: (b <= a), L))"
28,2/26/2016 18:20:55,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y: x if(x>y) else y, L)",NaN,1st-year MSc,Zhongrong Jian,A53096102,zhjian@ucsd.edu,"reduce(lambda x,y: x+y, map(lambda x: x**2, L))","list(filter(lambda x: x <= a, L))"
29,2/26/2016 18:35:31,NaN,4n,9,None of the above,NaN,"reduce(lambda x,y: x if (x > y) else y, L)",NaN,MS first year,Runze Xu,A53092653,rux012@eng.ucsd.edu,"reduce(lambda x,y: x+y, map(lambda x: x*x, L))","filter(lambda x: x <= a, L)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,3/12/2016 2:07:00,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda m,n: m if (m > n) else n, L)",NaN,MSc 2nd year,Nasha Zhai,A53082522,nzhai@ucsd.edu,"sum(map(lambda i: i*i, L))","filter(lambda i: i <=4, L)"
230,3/12/2016 2:07:05,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y:x if (x>y) else y,L)",NaN,MS 2 years,Chaitanya Baratam,A53104872,cbaratam@eng.ucsd.edu,"reduce(lambda x,y:x+y,map(lambda x:x*x,L))","filter(lambda x: x <= a,L)"
231,3/12/2016 2:07:58,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b : a if(a>b) else b,L)",NaN,MSc first year,Swetha Krishnakumar,A53087417,swk032@eng.ucsd.edu,"reduce(lambda a,b : a+b, map(lambda x: x**2,L)","filter(lambda x:x <=a,L)"
232,3/12/2016 2:08:20,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,Masters in CS first year,Ramkishore Swaminathan,A53089745,rswamina@eng.ucsd.edu,"\nreduce(lambda a,b: a+b,map(lambda x: x**2, L))","filter(lambda x: x <= a, L)"
233,3/12/2016 2:13:31,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,Masters first year,Sneha Priya Bhattaram,A53092331,spbhatta@eng.ucsd.edu,"reduce(lambda a,b: a+b,map(lambda x: x**2, L))","\nfilter(lambda x: x <= a, L)"
234,3/12/2016 2:17:35,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y: x if(x>y) else y, L)",NaN,"MSc, 1st year",Archana Radhakrishna,A53099070,arradhak@ucsd.edu,"reduce(lambda x,y: x+y*y, L)","filter(lambda x: x<=a , L)"
235,3/12/2016 2:17:37,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,MSc,Vrinda Gupta,A53091543,vrg001@eng.ucsd.edu,"reduce(lambda a,b: a+b*b ,L)","filter(lambda x: x<=a,L)"
236,3/12/2016 2:18:15,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x1, x2: x1 if (x1 > x2) else x2, L)",NaN,MS first year,Aravind Kumar Kumar,A53099973,akumark@eng.ucsd.edu,"reduce(lambda x1, x2: x1+x2, map(lambda z: z**...","filter(lambda z: z <= a, L)"
237,3/12/2016 2:19:33,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,MSc 1,Abhishek Majumdar,A53097687,abmajumd@eng.ucsd.edu,"reduce(lambda a,b: a+b,map(lambda x: x**2, L))","filter(lambda x: x <= a, L)"
238,3/12/2016 2:20:10,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,MS,SRIRAM MANOHAR,A53100761,srmanoha@eng.ucsd.edu,"reduce(lambda x,y: x+y*y,L)","filter(lambda x: x <= a, L)"
239,3/12/2016 2:20:50,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if (x > y) else y, L)",NaN,"MSc, 2",Joe Manley Gnanasekaran,A53096254,jgnanase@ucsd.edu,"reduce(lambda x, y: x + y, map(lambda x: x**2,...","filter(lambda x: x <= a, L)"
240,3/12/2016 2:33:10,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y:x if (x>y) else y,L)",NaN,"MS, 1st year",Srinivas Avireddy,A53101356,saviredd@eng.ucsd.edu,"reduce(lambda x,y:x+y,map(lambda x:x*x,L))","filter(lambda x: x <= a,L)"
241,3/12/2016 2:57:54,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda a,b: a if (a>b) else b, L)",NaN,MS - First year,Anshul Jain,A53096750,anj026@eng.ucsd.edu,"reduce(lambda x,y: x+y, map(lambda x,y: x*y, L...","filter(lambda x: x >=a, L)"
242,3/12/2016 3:38:15,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if x > y else y, L)",NaN,"MSc, half year",Zhengren Pan,A53102894,zhp007@eng.ucsd.edu,"reduce(lambda x, y: x + y, map(lambda x: x * x...","filter(lambda x: x <= a, L)"
243,3/12/2016 7:53:09,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x,y: x if x>y else y, L)",NaN,"MSc, 6 months",Rudra Pratap Singh,A53092651,rps001@eng.ucsd.edu,"reduce(lambda x,y: x+y, map(lambda x: x*x, L))","filter(lambda x:x <=a, L)"
244,3/12/2016 15:07:46,NaN,4n,9,None of the above,NaN,"maxval = reduce(lambda a,b: a if (a > b) else ...",NaN,MSc 1st,Zixin Xu,A97079187,zix001@ucsd.edu,"sumsquares = reduce(lambda x,y: x+y*y, L)","Out = filter(lambda x:x <= a, L)"
245,3/13/2016 1:02:21,NaN,4n,5,Independent and uncorrelated,NaN,"largest = reduce (lambda x ,y: x if (x > y) el...",NaN,MBA first year,Sabyasachi Nayak,a70001688,sabyasachi.nayak8@gmail.com,"sumsq = reduce (lambda x,y: x+y, map [ lambda ...",smalleq = filter ( lambda x: (lambda a: x<=a) ...
246,3/13/2016 17:40:02,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a>b) else b, L)",NaN,MS/less than 1 year,Yingzhi Wu,A53102471,yiw376@eng.ucsd.edu,"reduce(lambda a,b : a + b, map (lambda a: a * ...","filter(lambda x: x <=a, L)"
247,3/14/2016 18:42:04,NaN,n,3,Dependent and uncorrelated,NaN,"reduce(lambda a,b: a if (a > b) else b, L)",NaN,the second year master student @CSE,wenjia ouyang,A11069530,weouyang@eng.ucsd.edu,"reduce(lambda x, y: x*x+y*y, L)","filter(lambda x: ! ( x>a ), L)"
248,3/17/2016 21:54:37,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if (x > y) else y, L)",NaN,"MSc, 1",Zhenchao Gan,A53092819,zhgan@eng.ucsd.edu,"reduce(lambda x, y: x + y, map(lambda x: x * x...","filter(lambda x: x <= a, L)"
249,3/24/2016 17:21:04,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda u,v:u if (u>v) else v, L)",NaN,PhD/1,Vikas Sakaray,A53090014,vsakaray@eng.ucsd.edu,"reduce(lambda r,s:r+s, map(lambda u:u*u, L))","filter(lambda x: x<=a, L)"
250,3/24/2016 17:22:50,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda u,v:u if (u>v) else v, L)",NaN,PhD/1,Vikas Sakaray,A53090014,vsakaray@eng.ucsd.edu,"reduce(lambda r,s:r+s, map(lambda u:u*u, L))","filter(lambda x: x<=a, L)"
251,3/28/2016 18:19:59,NaN,n,5,Dependent and correlated,NaN,"reduce(lambda a,b: a if (a>b) else b, L)",NaN,PhD 2nd year,Larry Muhlstein,A53070548,lmuhlstein@ucsd.edu,"reduce(lambda a,b: a+b, map(lambda a:a**2, L))","filter(lambda x:a>x, L)"
252,3/29/2016 0:02:02,NaN,4n,5,Dependent and correlated,NaN,"f = lambda a,b: a if ( a >b) else b ; reduc...",NaN,"graduate student, half a year",Linqi Guo,A53104231,lig010@eng.ucsd.edu,"result = filter( lambda x: x ^ 2, L); reduce(...","output = filter(lambda x: x <= a, L )"
253,3/29/2016 3:12:12,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda x,y:max(x,y), L)",NaN,MS Electrical Engineering <1 year,Daniel Riley,A10730856,dgriley@ucsd.edu,"reduce(lambda x,y: x+y,map(lambda z: z*z,L))","filter(lambda x: x<= a,L)"
254,3/29/2016 13:35:31,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda a,b :a if a>b else b,L)",NaN,MSc 1,Joshua Neighbor,A53105202,jwneighb@eng.ucsd.edu,"reduce(lambda a,b : a+b,map(lambda x : pow(x,2...","filter(lambda c: c<=a,L)"
255,3/29/2016 13:46:33,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda x,y: x if x>y else y, L)",NaN,MSc 1st year,Yunsheng Li,A53086891,yul554@ucsd.edu,"reduce(lambda x,y:x+y, map(lambda i: i*i, L))",filter(lambda L: L>a)
256,3/29/2016 23:20:51,NaN,4n,6,None of the above,NaN,"reduce(lambda x,y:x if (x>y) else y,L)",NaN,PhD Year 4,Timothy Lew,A53020603,tflew@ucsd.edu,"reduce(lambda x,y: x+y , map(lambda x:x*x,L))","filter(lambda x:x<=a,L)"
257,3/31/2016 18:56:43,NaN,4n,9,Dependent and correlated,NaN,"reduce(lambda x, y: x if x>y else y, L)",NaN,3rd year NanoEngineering PhD,Zihan Xu,A53044451,zix009@ucsd.edu,"reduce(lambda x, y: x + y**2, L)","filter(lambda x: x <= a, L)"
258,4/4/2016 14:30:20,NaN,4n,9,Dependent and uncorrelated,NaN,"reduce(lambda x, y: x if (x > y) else y, L)",NaN,MSc 1st year,Mingyang Wang,A53100579,miw092@eng.ucsd.edu,"reduce(lambda x, y: x+y, map(lambda x: x**2, L))","filter(lambda x: x <= a, L)"

In [3]:
x=df[df['PID']=='A53089745']

In [4]:
for row in df.iterrows():
    D=dict(row[1])
    if 'Xiaojian' in D['Name']:
        print D['Input: a list of numbers L, output: the sum of the squares of the values in L']

sum = lambda list:reduce(lambda x,y:x+y, (map(lambda x:x**2,list)))
reduce(lambda x,y;x+y,(map(lambda x: x**2, L)))

In [9]:
!mv results.csv results.old.csv

In [12]:
!python grade.py EntranceExam2.csv

Exception:
2/25/2016 0:48:30,,4n,9,Dependent and correlated,,max(input),,MSc,Caroline Kim,A53104857,chk101@eng.ucsd.edu,sum(map(lambda x: x*x, input)),filter(lambda x: x <= a, L)
Exception:
2/25/2016 17:44:40,,4n,9,Dependent and uncorrelated,,max = lambda input: reduce(lambda x,y : x if(x>y) else y, input),,1st year MSc,Zhongrong Jian,A53096102,zhjian@ucsd.edu,sum = lambda input: reduce(lambda x,y: x+y, (map(lambda x:x**2, input))),seq = lambda input, a: list(filter(lambda x: x <= a, input))
Exception:
2/25/2016 17:46:49,,4n,9,Dependent and uncorrelated,,max = lambda list : reduce(lambda a, b : a if (a > b) else b, list),,MSc Computational Science (1st Year) - I did my undergrad in CS + Math,Juan Sidrach de Cardona Mora,A53096298,jsidrach@ucsd.edu,sumSq = lambda list : reduce(lambda a, b : a + b, map(lambda x : x * x, list)),filterList = lambda L, a : list(filter(lambda b : (b <= a), L))
Exception:
2/25/2016 17:48:32,,4n,9,Dependent and uncorrelated,,maxL = lambda L : reduce (lambda a,b : a if (a > b) else b, L),,1st year master,Lingyi Kong,A97010449,l1kong@ucsd.edu,sqSum = lambda L : reduce (lambda a,b : a + b, map(lambda x: x**2,L)),smallL = lambda L,a : filter (lambda x : x < a, L)
Exception:
2/25/2016 17:52:03,,4n,9,Dependent and uncorrelated,,maxL = lambda L : reduce (lambda a,b : a if (a > b) else b, L),,1st year Master,Lingyi Kong,A97010449,l1kong@ucsd.edu,sqSum = lambda L : reduce (lambda a,b : a + b, map(lambda x: x**2,L)),smallL = lambda L,a : filter(lambda x : x <= a, L)
Exception:
2/25/2016 18:11:26,,4n,9,Dependent and uncorrelated,,max = lambda L : reduce(lambda a,b : a if (a > b) else b, L),,First year graduate student,Lu Yu,a53107397,luy018@ucsd.edu,SoQ = lambda L : reduce (lambda x,y : x+y, map(lambda x : x**2, L)),listfilter = lambda L, a : list(filter(lambda b: (b <= a), L))
Exception:
2/25/2016 19:44:45,,4n,5,Independent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b,[1,2,3,4,5,6]),,MSc CSE 1st year/4 year BSc in Statistics,Shen Ting ANg,A53095324,s3ang@eng.ucsd.edu,reduce(lambda x,y:x+y,map(lambda x:x**2,[1,2,3,4,5,6])),filter(lambda x,a=3:x <=a,[1,2,3,4,5,6])
Exception:
2/26/2016 13:28:44,,4n,9,Dependent and correlated,,max = lambda list: reduce(lambda x,y:x if(x>y) else y, list),,MSc 2 years,Xiaojian Jin,A53104909,xij049@ucsd.edu,sum = lambda list:reduce(lambda x,y:x+y, (map(lambda x:x**2,list))),smallereq = lambda list, a: list(filter(lambda x:x<=a,list))
  File "run.py", line 3
    output= lambda a L:filter(lambda b: b<=a,L)
                     ^
SyntaxError: invalid syntax
Exception:
2/26/2016 13:48:25,,4n,9,Dependent and correlated,,f=lambda x: max(x),,1st year Master,Yilin Zhai,A53103154,yizhai@ucsd.edu,f= lambda x: sum(map(lambda a: a**2,x)),f= lambda a L:filter(lambda b: b<=a,L)
Exception:
2/26/2016 19:26:37,,4n,9,Dependent and uncorrelated,,result = max(L, key=lambda x:int(x)),,two years' M.s. in statistics,Xinrui Li,A53106153,xil430@ucsd.edu,result = sum(map(lambda x:x*x, L)),result = filter(lambda x: x <= a, L)
Exception:
2/26/2016 20:53:48,,4n,5,Dependent and uncorrelated,,reduce( lambda a,b: a if (a > b) else b,  L),,PhD 2nd year,Man Song,A53066657,mas065@ucsd.edu,sum(map(lambda x: x**2, L)),filter(lambda x: x<=a, L )
Exception:
2/27/2016 17:42:18,,4n,9,Dependent and correlated,,f=lambda L: max(L),,1st year Master,Yilin Zhai ,A53103154,yizhai@ucsd.edu,f=lambda L: sum(map((lambda x: x**2), L)),f=filter(lambda x: x<a, L)
Exception:
2/28/2016 1:09:57,,4n,9,Dependent and correlated,,reduce(lambda x, y : max(x, y), L),,MS, first year,Jie Fu,A53102444,jif052@eng.ucsd.edu,reduce(lambda x, y : x + y, map(lambda x : x*x, L)),filter(lambda x: x >= a, L)
Exception:
2/28/2016 17:02:07,,4n,9,Dependent and uncorrelated,,ans = reduce(lambda x, y: x if x > y else y, L),,UG 3.5 years,Eduardo Ramirez,A98043244,eduardo@ucsd.edu,ans = reduce(lambda a,y: a + (y**2), L, 0),ans = reduce(lambda x,y: [y]+x if y <= a else x, L, [])
Exception:
2/28/2016 17:02:30,,4n,9,Dependent and uncorrelated,,out = reduce(lambda x, y: max(x, y), L),,M.S. Computer Science,Jesse Qin,A10688717,jeqin@eng.ucsd.edu,out = reduce(lambda x, y: x + y**2, L, 0),out = reduce(lambda x, y: [y] + x if y <= a else x , L, [])
Exception:
2/29/2016 15:13:02,,2n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if(a>b) else b, L),,MS, 1st year,Seam Lee,A10029832,yhl014@ucsd.edu,sum(map(lambda x: x*x, L)),filter(lambda x: 1 if(x<=a) else 0, L)
Exception:
2/29/2016 17:03:51,,4n,9,Dependent and uncorrelated,,max(L),,MSc in Computer Engineering for 1.5 years,Yuchun Li,A53063718,yul352@eng.ucsd.edu,sum([x**2 for x in L]),[x for x in L if x <= a]
Exception:
3/1/2016 2:44:55,,4n,5,Dependent and uncorrelated,,reduce(lambda x, y: x if x >= y else y, L)  # equivalently, we could just use "max(L)",,First Year PhD,Andrew Leverentz,A53096478,aleveren@eng.ucsd.edu,sum(x**2 for x in L),[x for x in L if x <= a]
Exception:
3/1/2016 15:53:15,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,first year Master,Feichao,A53091625,feqian@ucsd.edu,reduce(lambda x, y: x + y*y, [0]+L ),filter(lambda x: x >= a, L)
Exception:
3/2/2016 18:43:34,,4n,9,Dependent and uncorrelated,,max(L),,MSc. in Computer Engineering for 1.5 years,Yuchun Li,A53063718,yul352@eng.ucsd.edu,sum([x**2 for x in L]),[x for x in L if x <= a]
  File "run.py", line 3
    output=reduce(lambda x,y;x+y,(map(lambda x: x**2, L)))
                            ^
SyntaxError: invalid syntax
Exception:
3/2/2016 18:54:06,,4n,9,Dependent and uncorrelated,,reduce(lambda x, y: x if(x>y) else y, L),,MSc,Xiaojian Jin,A53104909,xij049@ucsd.edu,reduce(lambda x,y;x+y,(map(lambda x: x**2, L))),list(filter(lambda x: x<=a,L))
Exception:
3/3/2016 0:00:11,,4n,9,Dependent and uncorrelated,,reduce (lambda a,b : a if (a > b) else b, L),,Msc first year,Jie Fu,A53102444,jif052@eng.ucsd.edu,reduce (lambda x, y : x + y, map(lambda x:x**2, L)),result = filter (lambda x : x >=a, L)
Exception:
3/3/2016 0:00:19,,4n,9,Dependent and uncorrelated,,reduce (lambda a,b : a if (a > b) else b, L),,Msc 1st year,Jingwen Xie,A53103415,jix111@eng.ucsd.edu,reduce (lambda x, y : x + y, map(lambda x:x**2, L)),result = filter (lambda x : x >=a, L)
Exception:
3/3/2016 17:46:05,,4n,9,Dependent and uncorrelated,,reduce (lambda max1, max2 : max1 if (max1 > max2) else max2, L),,MSc,Jingwen Xie,A53103415,jix111@ucsd.edu,reduce (lambda num1, num2 : num1 + num2, map (lambda num1:num1**2, L)),filter (lambda num:num >= a, L)
Exception:
3/5/2016 17:44:31,,4n,9,Dependent and uncorrelated,,max( L , key=lambda x:int(x) ),,2 years' statistics master,Xinrui Li,A53106153,xil430@ucsd.edu,sum( map( lambda x:x*x , L) ),filter( lambda x: x <= a , L)
  File "run.py", line 3
    output=list(map(lambda x: if (x<=a) x, L))
                               ^
SyntaxError: invalid syntax
Exception:
3/6/2016 1:36:42,,4n,9,Dependent and correlated,, reduce(lambda a,b: a if (a > b) else b, L),,MSc, one year,Xiaoying Gao,A53101876,xig060@eng.ucsd.edu,reduce(lambda x, y: x+y,  L),list(map(lambda x: if (x<=a) x, L))
Exception:
3/7/2016 0:07:36,,2n,5,Dependent and uncorrelated,,reduce(lambda x,y:x if x>y else y,L),,Msc,Jialong Li,A53105937,jil653@eng.ucsd.edu,reduce(lambda x,y:x+y,map(lambda x:x**2,L)),filter(lambda x:x<a,L)
Exception:
3/7/2016 1:58:30,,2n,9,Dependent and correlated,,reduce(lambda x, y: x if (x > y) else y, L),,3rd year Ph.D in Math,Jingwen Liang,a53051532,jil343@ucsd.edu,reduce(lambda x , y : x ** 2 + y ** 2, L),filter(lambda x: x <= a, L)
Exception:
3/7/2016 16:35:58,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b , L),,MSc 1st,Moojin Chae,A53102484,mochae@ucsd.edu,reduce(lambda x, y: x*x+y*y, L),filter(lambda x: x <= a, L)
Exception:
3/7/2016 17:49:21,,4n,9,Dependent and correlated,,reduce (lambda a,b : a if (a > b) else b, L),,MSc 1,Yihong Zhang,A53097346,yiz474@eng.ucsd.edu,reduce (lambda a,b : a+b, L),filter (lambda x: x<=a, L)
Exception:
3/8/2016 13:21:12,,4n,9,Dependent and uncorrelated,,reduce(lambda a, b: a if (a > b) else b, L),,MS 1 year,Songyang Li,A53097969,sol070@eng.ucsd.edu,reduce(lambda x, y: x+y, map(lambda x:x**2, L)),result = filter (lambda x: x >=a, L)
Exception:
3/8/2016 14:38:05,,2n,9,Dependent and uncorrelated,,reduce(lambda x,y: x if (x>y) else y, L),,PhD 1,Xiaojing Xu,A53099643,xix068@ucsd.edu,reduce(lambda x,y: x+y, map(lambda x: x**2, L) ),filter(lambda x: x>a, L)
Exception:
3/8/2016 15:22:39,,4n,5,Dependent and correlated,,reduce(lambda x,y : y if x < y else x,L),,First Year PhD,William Greenwald,A53092095,billgreenwald@ucsd.edu,reduce(lambda x,y: x+y,map(lambda x: x*x, L)),filter(lambda x: x<a,L)
Exception:
3/8/2016 19:41:05,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,Masters first year,Ramkishore Swaminathan,A53089745,rswamina@eng.ucsd.edu,sum(map(lambda x: x**2, L)),filter(lambda x: x < a, L)
Exception:
3/9/2016 2:04:48,,4n,9,Dependent and uncorrelated,,L = [2,10,4,5,11,2]
reduce(lambda x,y: x if (x>y) else y, L),,Ph.D. 1st Year,Jad Kanbar,A53012089,jkanbar@ucsd.edu,L = [1,2,3,4,5,6]
reduce(lambda x,y: x+y, map(lambda x: x * x, L)),L = [2,10,4,11,6,2]
a = 5
filter(lambda x: x<a, L)
  File "run.py", line 3
    output=map(lambda x: x if (x > a), L)
                                     ^
SyntaxError: invalid syntax
Exception:
3/9/2016 2:12:56,,4n,9,Dependent and correlated,,reduce(lambda a,b: a if (a > b) else b, L),,Msc, 1 year,Adithya Seshasayee,53104691,aseshasa@eng.ucsd.edu,reduce(lambda a,b: a**2 + b**2, L),map(lambda x: x if (x > a), L)
Exception:
3/9/2016 4:35:36,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,MS and 2 years,Sneha Priya Bhattaram,A53092331,spbhatta@eng.ucsd.edu,sum(map(lambda x: x**2, L)),filter(lambda x: x < a, L)
  File "run.py", line 3
    output=map(lambda x: x if (x<= a), L)
                                     ^
SyntaxError: invalid syntax
Exception:
3/9/2016 22:36:29,,4n,9,Dependent and correlated,,reduce(lambda x,y: x if (x > y) else y, L),,Msc., 1 year,Adithya Seshasayee,A53104691,aseshasa@eng.ucsd.edu,(reduce(lambda x,y: (x**2 + y**2)**0.5, L))**2,map(lambda x: x if (x<= a), L)
Exception:
3/10/2016 6:54:24,,4n,9,Dependent and uncorrelated,,reduce(lambda x,y: x if (x > y) else y, L),,MS Computer Science,SRIRAM MANOHAR,A53100761,srmanoha@eng.ucsd.edu,sum(map(lambda x: x**2, L)),filter(lambda x: x < a, L)
Exception:
3/10/2016 17:09:33,,4n,9,Dependent and uncorrelated,,reduce(lambda x,y: x if (x>y) else y, L),,MS in ECE (expected to graduate in 2017),Saurabh Kulkarni,A53099844,s3kulkar@eng.ucsd.edu,reduce(lambda x,y: x+y, map(lambda x,y: x*y, L,L)),filter(lambda x: x>=a, L)
Exception:
3/10/2016 18:23:20,,8n,9,Dependent and correlated,,reduce(lambda a,b: max(a,b),L),,First Year Ms,Dawei Wang,A53094262,daw068@ucsd.edu,reduce(lambda a,b: a+b,L),filter(lambda x: x <=a,L)
Exception:
3/10/2016 22:47:42,,4n,9,Dependent and uncorrelated,,reduce (lambda x,y: x if x>y else y,L),,MSc 1,Abhishek Majumdar,A53097687,abmajumd@ucsd.edu,sum(map(lambda x:x**2 , L) ),filter(lambda x: x <= a, L)
Exception:
3/10/2016 23:11:47,,4n,9,Dependent and uncorrelated,,reduce(lambda x, y: x if (x > y) else y, L),,MSc, 2,Joe Manley Gnanasekaran,A53096254,jgnanase@ucsd.edu,sum(map(lambda x: x**2, L)),filter(lambda x: x <= a, L)
Exception:
3/11/2016 0:27:23,,4n,9,Dependent and uncorrelated,,reduce(lambda x,y: x if (x > y) else y , L),,MSc 1,Aditya Suresh kumar,A53092425,asureshk@ucsd.edu,sum(map(lambda x: x*x,L)),filter(lambda x: x<= a,L)
  File "run.py", line 3
    output=filter(lambda x: <a, L)
                            ^
SyntaxError: invalid syntax
Exception:
3/11/2016 0:36:37,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if(a>b) else b, L),,MSc,  First year,Lenord Melvix Joseph Stephen Max,A53092538,lmelvix@ucsd.edu,sum(map(lambda a: a**2, L)),filter(lambda x: <a, L)
Exception:
3/11/2016 2:51:23,,4n,9,Dependent and correlated,,reduce( lambda a,b: a if (a > b) else b, L ),,MSc 2nd,Linjie Li,A53070599,lil121@ucsd.edu,reduce(lambda x, y: x*x+y*y, L),filter(lambda x: x <= a, L)
Exception:
3/11/2016 3:44:23,,4n,9,Dependent and uncorrelated,,reduce(lambda x,y: x if (x>y) else y, L),,MS, 1 year,Rakshit Wadhwa,A53100056,rawadhwa@ucsd.edu,reduce(lambda x,y: x + y*y, L, 0) ,reduce(lambda x,y: (x + 1) if (y <= a) else x, L,0)
  File "run.py", line 4
    output2 = reduce(lambda x, y : x + y, map (lambda x: x * x, L))
          ^
SyntaxError: invalid syntax
Exception:
3/11/2016 15:37:32,,4n,3,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,1st year MS CS student,Shalini Kedlaya,A53090836,skedlaya@ucsd.edu,reduce((lambda x, y: x +y), map(lambda x: x*x, L),list(filter(lambda x: x <=a, L ))
  File "run.py", line 4
    output2 = reduce(lambda x, y : x + y, map (lambda x: x * x, L))
          ^
SyntaxError: invalid syntax
Exception:
3/11/2016 17:53:34,,4n,9,Dependent and uncorrelated,,reduce( lambda a,b: a if (a > b) else b, L),,MS 1st year,Tanvi Nabar,A53098349,tgnabar@ucsd.edu,reduce (lambda a, b: a+b , (map(lambda x: x*x, L)),list(filter(lambda x: (x <= a), L))
Exception:
3/11/2016 20:01:09,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,2nd year master,Pengbo Li,A53079916,pel034@ucsd.edu,sum(map(lambda x:x*x,L)),filter(lambda x: x <= a, L)
Exception:
3/11/2016 20:49:13,,4n,9,Dependent and correlated,,reduce(lambda x,y: x if x>y else y, L, 0),,MS in CS, 2nd year,Juliana Curtis,A53064429,jccurtis@ucsd.edu,reduce(lambda x,y: x + y**2, L, 0),filter(lambda x: x < a, L)
Exception:
3/11/2016 22:03:40,,4n,9,Dependent and uncorrelated,,reduce(lambda x , y : x if (x > y) else y , L),,M.S. Computer Science, 2 years,Vamsi Krishna Cheekatimalla,A53099416,vcheekat@ucsd.edu,reduce(lambda x , y : x + y , map(lambda x : x * x , L)),filter(lambda x : x < a , L)
Exception:
3/12/2016 1:39:00,,4n,9,Dependent and uncorrelated,,reduce(lambda m,n: m if (m > n) else n, L),,Master in Statistics,Kuangyi Yang,A53083212,kuy006@ucsd.edu,sum(map(lambda i : i*i , L)),filter(lambda i: i <= 4, L)
Exception:
3/12/2016 2:02:49,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L)
,,MS,SRIRAM MANOHAR,A53100761,srmanoha@eng.ucsd.edu,reduce(lambda x,y: x+y*y,L),filter(lambda x: x < a, L)
Exception:
3/12/2016 2:07:00,,4n,9,Dependent and uncorrelated,,reduce(lambda m,n: m if (m > n) else n, L),,MSc 2nd year,Nasha Zhai,A53082522,nzhai@ucsd.edu,sum(map(lambda i: i*i, L)),filter(lambda i: i <=4, L)
  File "run.py", line 4
    output2 = reduce(lambda x, y : x + y, map (lambda x: x * x, L))
          ^
SyntaxError: invalid syntax
Exception:
3/12/2016 2:07:58,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b : a if(a>b) else b,L),,MSc first year,Swetha Krishnakumar,A53087417,swk032@eng.ucsd.edu,reduce(lambda a,b : a+b, map(lambda x: x**2,L),filter(lambda x:x <=a,L)
  File "run.py", line 3
    output=
          ^
SyntaxError: invalid syntax
Exception:
3/12/2016 2:08:20,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,Masters in CS first year,Ramkishore Swaminathan,A53089745,rswamina@eng.ucsd.edu,
reduce(lambda a,b: a+b,map(lambda x: x**2, L)),filter(lambda x: x <= a, L)
  File "run.py", line 3
    output=
          ^
SyntaxError: invalid syntax
Exception:
3/12/2016 2:13:31,,4n,9,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,Masters first year,Sneha Priya Bhattaram,A53092331,spbhatta@eng.ucsd.edu,reduce(lambda a,b: a+b,map(lambda x: x**2, L)),
filter(lambda x: x <= a, L)
Exception:
3/12/2016 2:57:54,,4n,9,Dependent and correlated,,reduce(lambda a,b: a if (a>b) else b, L),,MS - First year,Anshul Jain,A53096750,anj026@eng.ucsd.edu,reduce(lambda x,y: x+y, map(lambda x,y: x*y, L, L)),filter(lambda x: x >=a, L)
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    output= reduce (lambda x,y: x+y, map [ lambda a : a**2 , L])
TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'
Exception:
3/13/2016 1:02:21,,4n,5,Independent and uncorrelated,,largest = reduce (lambda x ,y: x if (x > y) else y, L),,MBA first year,Sabyasachi Nayak,a70001688,sabyasachi.nayak8@gmail.com,sumsq = reduce (lambda x,y: x+y, map [ lambda a : a**2 , L]),smalleq = filter ( lambda x: (lambda a: x<=a) , L)
  File "run.py", line 3
    output=filter(lambda x: ! ( x>a ), L)
                            ^
SyntaxError: invalid syntax
Exception:
3/14/2016 18:42:04,,n,3,Dependent and uncorrelated,,reduce(lambda a,b: a if (a > b) else b, L),,the second year master student @CSE,wenjia ouyang,A11069530,weouyang@eng.ucsd.edu,reduce(lambda x, y: x*x+y*y, L),filter(lambda x: ! ( x>a ), L)
Exception:
3/28/2016 18:19:59,,n,5,Dependent and correlated,,reduce(lambda a,b: a if (a>b) else b, L),,PhD 2nd year,Larry Muhlstein,A53070548,lmuhlstein@ucsd.edu,reduce(lambda a,b: a+b, map(lambda a:a**2, L)),filter(lambda x:a>x, L)
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    output= lambda a,b: a if ( a >b) else b ;    reduce(f, L)
NameError: name 'f' is not defined
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    output= filter( lambda x: x ^ 2, L);  reduce( lambda x,y : x + y, result);
NameError: name 'result' is not defined
Exception:
3/29/2016 0:02:02,,4n,5,Dependent and correlated,,f = lambda a,b: a if ( a >b) else b ;    reduce(f, L),,graduate student, half a year,Linqi Guo,A53104231,lig010@eng.ucsd.edu,result = filter( lambda x: x ^ 2, L);  reduce( lambda x,y : x + y, result);,output = filter(lambda x: x <= a, L )
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    output=filter(lambda L: L>a)
TypeError: filter expected 2 arguments, got 1
Exception:
3/29/2016 13:46:33,,4n,9,Dependent and correlated,,reduce(lambda x,y: x if x>y else y, L),,MSc 1st year,Yunsheng Li,A53086891,yul554@ucsd.edu,reduce(lambda x,y:x+y, map(lambda i: i*i, L)),filter(lambda L: L>a)

In [14]:
!wc results.csv

     260     556   19277 results.csv